---
title: "writing_functions"
author: "Xiaoting Tang"
date: "`r Sys.Date()`"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
set.seed(12345)
```


# Z scores

```{r}
x_vec = rnorm(20, mean = 5, sd = .3)
```

Compute Z scores for `x_vec`.

```{r}
(x_vec - mean(x_vec)) / sd(x_vec)
```

Write a function to do this!

```{r}
z_score = function(x) {
  
  if (!is.numeric(x)){
    stop("Argument should be numbers")
  } else if (length(x) < 2) {
    stop("You need at least 2 numbers to get z scores")
  }
  
  z = (x - mean(x)) / sd(x)
  
  z
}
```

Check that this works.

```{r}
z_score(x = x_vec)
```

Keep checking.

```{r}
z_score(x = 3)

z_score(c("my", "name", "is", "jeff"))

z_score(c(TRUE, TRUE, FALSE, TRUE))

z_score(iris)
```

### Multiple outputs.

Write a function that returns the mean and the sd from a sample of numbers

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)){
    stop("Argument should be numbers")
  } else if (length(x) < 2) {
    stop("You need at least 2 numbers to get z scores")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
}
```

Double check I did this right...

```{r}
mean_and_sd(x_vec)
```


### Start getting means and sds

```{r}
x_vec = rnorm(n = 30, mean = 5, sd = 0.5)

tibble(
  mean = mean(x_vec),
  sd = sd(x_vec)
  )

```

Let's write a function that uses `n`, a true mean, and true SD as inputs.

```{r}
sim_mean_sd = function(n_obs ,mu, sigma) {

  x_vec = rnorm(n = n_obs, mean = mu, sd = sigma)

  tibble(
  mean = mean(x_vec),
  sd = sd(x_vec)
  )
  
  
}

sim_mean_sd(30, 5, .5)
```


### LoTR words

```{r}
fellowship_ring = 
  readxl::read_excel("data/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring")


lotr_load_and_tidy = function(path = "data/LotR_Words.xlsx", cell_range, movie_name) {
  
  movie_df = 
    readxl::read_excel(path, range = cell_range) |>
    janitor::clean_names() |>
    mutate(race = str_to_lower(race),
           movie = movie_name) |>
    janitor::clean_names() |>
    pivot_longer(
      female:male,
      names_to = "sex",
      values_to = 
    )
  
  movie_df
  
}

lotr_load_and_tidy(cell_range = "B3:D6", movie_name = "fellowship_ring")
```










